# Dependencies
# markdown: redcarpet
# highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Setup
title: LeonKong
tagline: "Chaewon Kong's Development Blog"
description: "Chaewon Kong's Blog. JavaScript, React, NodeJS, Algorithms, Technologies and Computer Sciens"
url: https://chaewonkong.github.io
baseurl: /

author:
  name: "Chaewon Kong"
  url: https://twitter.com/mdo

paginate: 1

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/poole/hyde
